### ISSUE TITLE
The GitLab backend does not support the Editorial Workflow.

### ISSUE THREAD

**Issue by ferryarman** [PHPoole/Cecil#29]
Testing the blog, looks promising:
https://phpoole-cecil-demo.netlify.com/admin/#/

However, after deploying `PHPoole` on Netlify, created a user for Netlify identity & when about to access `https://firstnearblog.netlify.com/admin/#/`

There's a toast message:
```
The GitLab backend does not support the Editorial Workflow.
```
I saw this error has been mentioned in different repo: https://github.com/netlify/netlify-cms/issues/568

Or, should I try use other non Gitlab repository ?

**Comment by Narno** [comment]
Hello @ferryarman,

I confirm:

> Note: Editorial workflow works with GitHub repositories only. Support for other Git hosts is coming soon.

https://www.netlifycms.org/docs/add-to-your-site/#editorial-workflow

You have 2 choices:
1. Stay on GitLab and disable `publish_mode: editorial_workflow` in [configuration file](https://github.com/PHPoole/Cecil/blob/master/static/admin/config.yml#L4)
2. Switch to GitHub

Thank you :-)
